# Generated by Django 4.2.2 on 2023-06-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fondateur',
            fields=[
                ('id_fondateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField(max_length=50)),
                ('postnom', models.TextField(max_length=50)),
                ('prenom', models.TextField(max_length=50)),
                ('photo', models.ImageField(upload_to='photo_fondateur')),
                ('dateNaissance', models.DateField()),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 't_fondateur',
            },
        ),
        migrations.CreateModel(
            name='PartiPolitique',
            fields=[
                ('id_parti', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField(max_length=50)),
                ('historique', models.TextField(max_length=500)),
                ('service', models.TextField(max_length=500)),
                ('anneeCreation', models.DateField()),
                ('logo', models.ImageField(upload_to='logo_parti')),
                ('fondateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_App.fondateur')),
            ],
            options={
                'db_table': 't_partiPolitique',
            },
        ),
    ]
